version: '3.7'
services:
    registry:
        image: registry:2
        restart: always
        volumes:
            - registry-data:/var/lib/registry
        networks:
             - traefik
        labels:
            - traefik.frontend.rule=Host:${HOSTNAME:-registry}
            - traefik.enable=true
            - traefik.port=5000
volumes:
    registry-data:
networks:
    traefik:
        external:
            name: traefik
